# coding: utf-8
# Generated by Django 1.9 on 2016-01-04 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_common', '0002_allegrouserscache'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_type',
            field=models.PositiveSmallIntegerField(choices=[(0, b'Local'), (1, b'Facebook')], default=0),
        ),
    ]
