# coding: utf-8
# Generated by Django 1.9.2 on 2016-02-08 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_common', '0004_taskscheduler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllegroUsersCache',
        ),
    ]
