# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-08 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_common', '0005_auto_20160208_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='provider',
            field=models.IntegerField(choices=[(0, b'allegro'), (1, b'ebay'), (2, b'all')], default=0),
        ),
    ]
