# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-13 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_common', '0006_category_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
