# coding: utf-8
# Generated by Django 1.9 on 2016-01-04 02:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ac_common', '0002_allegrouserscache'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.PositiveSmallIntegerField(choices=[(0, b'Allegro'), (1, b'Ebay')])),
                ('advanced', models.BooleanField(default=False)),
                ('statistics', models.BooleanField(default=False)),
                ('hint', models.BooleanField(default=False)),
                ('prediction', models.BooleanField(default=False)),
                ('histogram', models.BooleanField(default=False)),
                ('trends', models.BooleanField(default=False)),
                ('json_dump', models.TextField(max_length=1500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ac_common.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', related_query_name=b'result', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Triggers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.PositiveSmallIntegerField(choices=[(0, b'Price above'), (1, b'Quantity left'), (2, b'Quantity left percent')])),
                ('provider', models.IntegerField(choices=[(0, b'Allegro'), (1, b'Ebay')])),
                ('auction_id', models.IntegerField()),
                ('value', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', related_query_name=b'trigger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
