# coding: utf-8
# Generated by Django 1.9 on 2016-01-04 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='provider',
            field=models.PositiveSmallIntegerField(choices=[(0, b'Allegro'), (1, b'Ebay'), (2, b'Allegro+Ebay')]),
        ),
        migrations.AlterField(
            model_name='triggers',
            name='provider',
            field=models.IntegerField(choices=[(0, b'Allegro'), (1, b'Ebay'), (2, b'Allegro+Ebay')]),
        ),
    ]
