# coding: utf-8
# Generated by Django 1.9 on 2016-01-09 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_engine', '0005_results_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
