# coding: utf-8
# Generated by Django 1.9 on 2016-01-09 14:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ac_engine', '0006_auto_20160109_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggers',
            name='on',
        ),
        migrations.RemoveField(
            model_name='triggers',
            name='state',
        ),
        migrations.RemoveField(
            model_name='triggers',
            name='value',
        ),
        migrations.AddField(
            model_name='triggers',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 9, 14, 56, 32, 260588, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triggers',
            name='date_finished',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='triggers',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triggers',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triggers',
            name='mode',
            field=models.PositiveSmallIntegerField(choices=[(0, b'Price above'), (1, b'Quantity left'), (2, b'Auction views')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triggers',
            name='mode_value',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triggers',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='triggers',
            name='time',
            field=models.PositiveSmallIntegerField(choices=[(0, b'1H'), (1, b'15M'), (2, b'5M'), (3, b'2M')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='results',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
