# coding: utf-8
# Generated by Django 1.9 on 2016-01-09 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_engine', '0008_auto_20160109_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggers',
            name='mode',
            field=models.PositiveSmallIntegerField(choices=[(0, b'price'), (1, b'quantity'), (2, b'views')]),
        ),
        migrations.AlterField(
            model_name='triggers',
            name='time',
            field=models.PositiveSmallIntegerField(choices=[(0, b'lazy'), (1, b'moderate'), (2, b'turbo'), (3, b'ultra_turbo')]),
        ),
    ]
