# coding: utf-8
# Generated by Django 1.9 on 2016-01-09 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_engine', '0009_auto_20160109_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('value', models.PositiveSmallIntegerField()),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_values', related_query_name=b'trigger_value', to='ac_engine.Triggers')),
            ],
        ),
    ]
