# coding: utf-8
# Generated by Django 1.9 on 2016-01-10 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_engine', '0010_triggervalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggers',
            name='task_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
